Foreground yes
TCPSocket 3310
TCPAddr 0.0.0.0
User clamav
DatabaseDirectory /var/lib/clamav
LogTime yes
MaxFileSize 110M
MaxScanSize 110M
StreamMaxLength 110M
ReadTimeout 300
CommandReadTimeout 300
SendBufTimeout 300
