export {
  clientIndustries,
  clientLanguages,
  clientOwners,
  clientPaymentTerms,
  clientSiteTypes,
  clientSources,
  clientStatuses,
  formatMoney,
  preferredContactMethods,
  type ClientActivity,
  type ClientContact,
  type ClientContactInput,
  type ClientCreatePayload,
  type ClientIndustry,
  type ClientQuoteSummary,
  type ClientRecord,
  type ClientSite,
  type ClientSiteInput,
  type ClientSiteType,
  type ClientStatus,
  type PreferredContactMethod
} from "@/types/client";
