# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main , develop]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
env:
  PORT: ${{secrets.PORT}}
  AUTHORITY: ${{secrets.AUTHORITY}}
  CLIENTID: ${{secrets.CLIENTID}}
  CLIENTSECRET: ${{secrets.CLIENTSECRET}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
#     services:
#       database-container:
#         image: mysql5.7
#         env:
#           MYSQL_PASSWORD: ${{secrets.MY_SQL_PWD}}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up node 
        uses: actions/setup-node@v2
        with:
          node-version: '12'


      - name: Build the docker-compose stack
        if: ${{ success() }}
        env:
          PORT: ${{secrets.PORT}}
          COMPOSE_FILE: docker-compose.ci.yml
          AUTHORITY: ${{secrets.AUTHORITY}}
          CLIENTID: ${{secrets.CLIENTID}}
          CLIENTSECRET: ${{secrets.CLIENTSECRET}}
          DB_HOST: ${{secrets.DB_HOST}}
          MY_SQL_PWD: ${{secrets.MY_SQL_PWD}}
        run: docker-compose build
          # - run: npm ci
          #   working-directory: gui
            
          # - run: npm run test:prod
          #   working-directory: gui
          # - run: npm run lint
          #   working-directory: gui
      - name: Check running containers
        env:
            PORT: ${{secrets.PORT}}
            AUTHORITY: ${{secrets.AUTHORITY}}
            CLIENTID: ${{secrets.CLIENTID}}
            CLIENTSECRET: ${{secrets.CLIENTSECRET}}

        if: ${{ success() }}
        run: docker ps -a
      
      # - name: Check logs
      #   env:
      #     PORT: ${{secrets.PORT}}
      #     AUTHORITY: ${{secrets.AUTHORITY}}
      #     CLIENTID: ${{secrets.CLIENTID}}
      #     CLIENTSECRET: ${{secrets.CLIENTSECRET}}
        
      #   if: ${{ success() }}
      #   run: docker logs backend-container
      - name: Run Docker Compose
        env:
          COMPOSE_FILE: docker-compose.ci.yml
          PORT: ${{secrets.PORT}}
          AUTHORITY: ${{secrets.AUTHORITY}}
          CLIENTID: ${{secrets.CLIENTID}}
          CLIENTSECRET: ${{secrets.CLIENTSECRET}}
          DB_HOST: ${{secrets.DB_HOST}}
          MY_SQL_PWD: ${{secrets.MY_SQL_PWD}}
        run: docker-compose up -d

      - name: Run backend tests
        env:
          COMPOSE_FILE: docker-compose.ci.yml
          PORT: ${{secrets.PORT}}
          AUTHORITY: ${{secrets.AUTHORITY}}
          CLIENTID: ${{secrets.CLIENTID}}
          CLIENTSECRET: ${{secrets.CLIENTSECRET}}
          DB_HOST: ${{secrets.DB_HOST}}
          MY_SQL_PWD: ${{secrets.MY_SQL_PWD}}
        if: ${{ success() }}
        # run: docker exec --workdir /backend backend-container npm i mocha chai sinon |
        #      docker exec --workdir /backend backend-container npm test
        run: docker-compose run -e PORT=${{secrets.PORT}} -e AUTHORITY=${{secrets.AUTHORITY}} -e CLIENTID=${{secrets.CLIENTID}} -e CLIENTSECRET=${{secrets.CLIENTSECRET}} -e MY_SQL_PWD=${{secrets.MY_SQL_PWD}} -e DB_HOST=${{secrets.DB_HOST}} backend npm test
      # - name: Run gui tests
      #   if: ${{ success() }}
      #   run: docker exec gui-container cd /gui && ng test && ng e2e && npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Release
        if: ${{ success() }}
        env:
          OWNER: AlejandroRNatal 
          REPO: ${{github.event.repository.name}}
        run: dev-tools/release.sh
